# Copyright (c) Jiaqi Liu.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
---
name: Documentation CI/CD

'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy-documentation:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lexical-website
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies, including the root ones
        run: |
          cd ../../
          npm install
          cd packages/lexical-website
          npm install
      - name: Build website
        run: npm run build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/lexical-website/build
          user_name: QubitPi
          user_email: jack20220723@gmail.com
